### ISSUE TITLE
Module keeps stopping

### ISSUE THREAD

**Issue by Jangomnz** [karloygard/hassio-addons#10]
After a HA update the xcomfort module keeps stopping with the following log:
Currently running Home Assistant 0.115.2

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:15:54] INFO: Starting xcomfortd version 0.3
2020/09/25 08:15:54 Connecting to MQTT broker 'tcp://core-mosquitto:1883' with id 'xcomfort'
2020/09/25 08:15:55 Connected to broker
2020/09/25 08:15:55 Opened HID device 0
2020/09/25 08:15:55 dropping wheel position on the ground: 1.9
2020/09/25 08:15:55 Device 6159984 (channel 0-'Bad Kj (7)') sent message (battery good, signal good, cyclic true) event 'value' with value 23.1
2020/09/25 08:15:55 CI HW/RF/FW revision: 0, 13.0, 0
2020/09/25 08:15:55 CI RF/Firmware release: 2.11, 2.05
2020/09/25 08:15:55 CI serial number: 7607213
2020/09/25 08:15:55 Unknown DPL format
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by Jangomnz** [comment]
I updated a new data point list as well, as I was thinking it had issues with this due to this line in the log:
2020/09/25 08:15:55 Unknown DPL format

**Comment by karloygard** [comment]
Did you upload the DPL file to the stick? Which MRF software did you use?

**Comment by Jangomnz** [comment]
Impressive responsetime :-)
I*m using MRF v. 2.66

**Comment by karloygard** [comment]
Did you upload the DPL to the xComfort stick? There is no longer any need to download the configuration file and copy it over to HA, etc.

**Comment by Jangomnz** [comment]
This might be the issue :-)  Was not aware of this change.  Is this done in MRF?

**Comment by karloygard** [comment]
Yes, same place as you download the DPL. You're given the option of sending to the stick.

**Comment by Jangomnz** [comment]
That seems to have solved the problem :-)  
Takk for lynrask service :-)
