### ISSUE TITLE
Got unexpected response from the API: Service not enabled

### ISSUE THREAD

**Issue by leifurg** [karloygard/hassio-addons#11]
Dear Karlyogar,
Hope it is ok i send this issue here, as i was about to give up on Xcomfort when i found this addon in Github.
i am new to Home assistant but decided to try after seeing your addon.
I am using Raspberry pi3 with CKOZ-00/13  USB stick, and on startup i get the error in the log here below
I attached the config and export file from MRF if that helps.
Maybe i am misunderstanding the setup but hope i can get this working.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:43:41] **ERROR: Got unexpected response from the API: Service not enabled**
[20:43:46] INFO: Starting xcomfortd version 0.26
[20:43:47] INFO: xcomfortd --client-id xcomfort --server tcp*****//*****@***** --hadiscoveryprefix homeassistant --eprom --file /config/Frigg22.txt --hadiscovery
2021/01/06 20:43:47 No devices found
[cmd] /run.sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.

[Frigg2.txt](https://github.com/karloygard/hassio-addons/files/5778143/Frigg2.txt)
![config](https://user-images.githubusercontent.com/76958523/103818879-3b304100-5061-11eb-8db3-c49036da2407.JPG)

**Comment by karloygard** [comment]
You need the CKOZ-00/14 stick, the 00/13 is just for configuring/adding/removing devices. You do need both USB sticks in order to be completely up and running with xComfort in any case.

**Comment by leifurg** [comment]
Thanks for a super quick reply, i will purchase the 00/14 and try again.

**Comment by karloygard** [comment]
I'm not sure what the "ERROR: Got unexpected response from the API: Service not enabled" is complaining about, though, you do have MQTT running, right?

**Comment by leifurg** [comment]
Yes MQTT is running and seems to be ok. I will test this again with correct USB stick which should arrive here after the weekend.
I will add comment after that test and hope it will do the trick.

**Comment by leifurg** [comment]
Dear Karloygard,
i got the correct USB stick and have set all up again, i can find devices in Home Assistant.
But there is this USB error here below and when i try to turn on a light nothing happens except the error as you can see in the log below @22:00:11

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:59:04] INFO: Starting xcomfortd version 0.26
[21:59:04] INFO: xcomfortd --client-id xcomfort --server tcp://*****@core-mosquitto:1883 --hadiscoveryprefix homeassistant --eprom --file /config/Frigg2A.dpl --hadiscovery
2021/01/21 21:59:04 Opened USB device vid=188a,pid=1101,bus=1,addr=4
2021/01/21 21:59:04 Connecting to MQTT broker 'tcp://core-mosquitto:1883' with id 'xcomfort'
2021/01/21 21:59:05 Connected to broker
2021/01/21 21:59:05 CI HW/RF/FW revision: 0, 13.0, 0
2021/01/21 21:59:05 CI RF/Firmware release: 2.11, 2.05
2021/01/21 21:59:06 CI serial number: 7666024
2021/01/21 21:59:06 handle_events: error: libusb: interrupted [code -10]
2021/01/21 21:59:15 Read datapoint list from eprom in 9.803825206s
2021/01/21 21:59:15 Sent MQTT autodiscover add for 8 devices and 8 datapoints
2021/01/21 22:00:11 MQTT message; topic: 'xcomfort/18/set/dimmer', message: '100'
2021/01/21 22:00:11 WARNING: command for datapoint 18 failed, state now unknown: General error: unknown error
2021/01/21 22:06:36 handle_events: error: libusb: interrupted [code -10]
2021/01/21 22:12:21 handle_events: error: libusb: interrupted [code -10]
2021/01/21 22:19:29 handle_events: error: libusb: interrupted [code -10]
2021/01/21 22:20:09 handle_events: error: libusb: interrupted [code -10]

**Comment by karloygard** [comment]
You should decide whether to read the datapoints list from file or eprom, don't use both. In this case, the eprom list will be used.

The error is reported by the CKOZ-00/14 stick, either because it couldn't send the message to datapoint 18, or because the datapoints list is incorrect. Have you updated the eprom datapoints list?

Also, you can turn on verbose to see a little more of what's going on.

**Comment by karloygard** [comment]
Did you figure it out?

**Comment by leifurg** [comment]
Yes finally last night i managed to review again and just uploaded again config to the stick and removed file name feom config and all works fine now.
Thanks for your help and creating this great addon. :)
