### ISSUE TITLE
Binary inputs defaults to false after restart.

### ISSUE THREAD

**Issue by dreeas** [karloygard/hassio-addons#13]
Once again, really appriciate your work with this addon. Have been waiting for this for years.

Found an issue with binary inputs defaulting to FALSE when restarting HA. 
Have a binary input for status on my garage doors. It is TRUE when closed but every time I restart HA it goes to FALSE thus showing both garage doors open. Have to cycle the inputs (opening/closing the garage doors) to get the correct feedback. 
Should not the MQTT broker remember last state?

Br
Andreas

**Comment by karloygard** [comment]
Try the freshly released 0.32, all MQTT messages are now retained.

**Comment by dreeas** [comment]
Great, thanks.
Statuses are now remembered during a restart.
