### ISSUE TITLE
CKOZ-00/03

### ISSUE THREAD

**Issue by terosm** [karloygard/hassio-addons#16]
Hi. I am trying to use your xcomfort addon in my HA. Have many xcomfort devices I want to test.
I try to use the CKOZ-00/03. Have used this device with another software earlier, IP-Symcon.

The addon repports;
[09:14:00] INFO: Starting xcomfortd version 0.36.1
[09:14:00] INFO: xcomfortd --client-id xcomfort --server tcp://*****@core-mosquitto:1883 --hadiscoveryprefix homeassistant --eprom --hadiscovery --verbose
2021/07/29 09:14:00 Starting xcomfortd, version 0.36.1
2021/07/29 09:14:00 Opened USB device 'vid=188a,pid=1101,bus=1,addr=6', packet size 19/9
2021/07/29 09:14:00 Connecting to MQTT broker 'tcp://core-mosquitto:1883' with id 'xcomfort'
2021/07/29 09:14:00 CONFIG: [b21b10]
[WARN]  [store]    memorystore wiped
2021/07/29 09:14:00 Connected to broker
2021/07/29 09:14:00 STATUS: [c31b10035c02b7]
2021/07/29 09:14:00 CI HW/RF/FW revision: 3, 9.2, 695
2021/07/29 09:14:00 CONFIG: [b21b00]
2021/07/29 09:14:01 STATUS: [c31b000902023c]
2021/07/29 09:14:01 CI RF/Firmware release: 9.02, 2.60
2021/07/29 09:14:01 CONFIG: [b20e00]
2021/07/29 09:14:01 STATUS: [c30e0000401ff7]
2021/07/29 09:14:01 CI serial number: 4202487
2021/07/29 09:14:01 CONFIG: [b20401]
2021/07/29 09:14:01 handle_events: error: libusb: interrupted [code -10]
2021/07/29 09:14:01 STATUS: [c31c0500000000]
2021/07/29 09:14:01 CONFIG: [b21e01]
2021/07/29 09:14:01 STATUS: [c31c0500000000]
2021/07/29 09:14:01 Reading datapoints list from eprom
2021/07/29 09:14:01 STATUS: [c3090196000000]
2021/07/29 09:14:05 handle_events: error: libusb: interrupted [code -10]
2021/07/29 09:14:31 handle_events: error: libusb: interrupted [code -10]
2021/07/29 09:14:34 handle_events: error: libusb: interrupted [code -10]
2021/07/29 09:14:50 handle_events: error: libusb: interrupted [code -10]
2021/07/29 09:15:47 handle_events: error: libusb: interrupted [code -10]

Some tip ?

**Comment by terosm** [comment]
I get these messages..
2021/07/29 09:52:08 RX: [c10b70002800000000421007]
2021/07/29 09:52:08 Received message from unknown datapoint 11
2021/07/29 09:52:08 Message not handled [c10b70002800000000421007]
2021/07/29 09:52:09 handle_events: error: libusb: interrupted [code -10]
2021/07/29 09:52:10 RX: [c10b70000000000000421009]
2021/07/29 09:52:10 Received message from unknown datapoint 11
2021/07/29 09:52:10 Message not handled [c10b70000000000000421009]
2021/07/29 09:52:15 RX: [c10870002300000000421009]
2021/07/29 09:52:15 Received message from unknown datapoint 8
2021/07/29 09:52:15 Message not handled [c10870002300000000421009]
2021/07/29 09:52:15 RX: [c10770002300000000471003]
2021/07/29 09:52:15 Received message from unknown datapoint 7
2021/07/29 09:52:15 Message not handled [c10770002300000000471003]
2021/07/29 09:52:17 handle_events: error: libusb: interrupted [code -10]
2021/07/29 09:52:19 RX: [c10770002300000000481005]
2021/07/29 09:52:19 Received message from unknown datapoint 7
2021/07/29 09:52:19 Message not handled [c10770002300000000481005]
2021/07/29 09:52:20 RX: [c1087000000000000043100b]
2021/07/29 09:52:20 Received message from unknown datapoint 8
2021/07/29 09:52:20 Message not handled [c1087000000000000043100b]

Do I have to use datapoint file ?
I read from eeprom today.

**Comment by karloygard** [comment]
Have you uploaded the DPL file to the stick?
> Datapoints can be read out from the eprom on the devices, which must be kept updated manually if and when devices are added. Consult the MRF manual (paragraph USB-RF-Communication Stick) for documentation on how to do this.

You can find the instructions on page 170/171 in http://www.eaton.eu/ecm/idcplg?IdcService=GET_FILE&allowInterrupt=1&RevisionSelectionMethod=LatestReleased&noSaveAs=0&Rendition=Primary&dDocName=PCT_1203382

**Comment by terosm** [comment]
Hi. Thanks for the fast response and answer. 
Yes I have uploaded my old USB stick with the command "Last komponenten på nytt".
Created a new datapoint 14 for testing of the upload. It is a dimmeraktuator. Also activated "Send gammel Status-melding".
The debug shows then:
2021/07/30 09:21:28 RX: [c10e7000140000000041100e]
2021/07/30 09:21:28 Received message from unknown datapoint 14
2021/07/30 09:21:28 Message not handled [c10e7000140000000041100e]

But from what I have seen from other posts it looks like the list are not read from the stick. Only answer with  STATUS: [c3090196000000]

Is there a big difference between my 00/03 and the new 00/14 regarding reading eprom ?

**Comment by karloygard** [comment]
Ah, the 00/03 is less tested. I'll inspect the logs above and see if I see anything interesting.

**Comment by austadt** [comment]
Sorry to bug in, but are you sure you have right clicked the stick and "Framstill datapunktliste"->overfør via RF? Sounds alot like you havent

Im using datapoint file, as it is way faster rebooting that way

30. jul. 2021 09:40 skrev Karl Anders Øygard ***@***.***>:

Ah, the 00/03 is less tested. I'll inspect the logs above and see if I see anything interesting.

**Comment by terosm** [comment]
That's ok !  
When using the "old" 00/03 this as I try, "overfør via RF" is not a choice.
It is  "Last komponenten på nytt" and "Fremstill datapunktliste -> filename.txt "

Where do you store this file ( which folder ) ? 
I am using HassOS and a NUC.

**Comment by karloygard** [comment]
> I'm using datapoint file, as it is way faster rebooting that way

Yeah, that will be substantially faster, reading from eprom is pretty slow.

**Comment by karloygard** [comment]
> When using the "old" 00/03 this as I try, "overfør via RF" is not a choice.
> It is "Last komponenten på nytt" and "Fremstill datapunktliste -> filename.txt "

Interesting, the 00/03 may not support storing the DPL file in the eprom at all?

> Where do you store this file ( which folder ) ?
> I am using HassOS and a NUC.

If I'm not mistaken, the file goes in the config folder.

**Comment by karloygard** [comment]
@terosm  I just released 0.37 which attempts to detect that the CI doesn't support reading from eprom. Can you give it a spin and see if it works as intended? It should log this:

```Warning: CI doesn't support extended commands, cannot read datapoints from eprom. Must use file instead```

**Comment by terosm** [comment]
Hi, try to upgrade today.
Getting " '4117215b_xcomfort' " vhen I try to do a backup before "oppdater".

**Comment by terosm** [comment]
Oppdater xComfort
Er du sikker på at du vil oppdatere xComfort til version 0.37 ?
Sikkerhetskopi
Lag en sikkerhetskopi av xComfort før du oppdaterer
'4117215b_xcomfort'
Avbryt
"Oppdater" is grey.

**Comment by karloygard** [comment]
Does anything show up in the logs?

**Comment by karloygard** [comment]
The DPL file should go in the `/config/` folder of hassio, and must be specified in the `datapoints_file` option in the xcomfortd configuration.

As mentioned, the 00/03 is less tested, so I'm very curious to hear how it works out for you.

**Comment by terosm** [comment]
I have two locations with xcomfort, so I will buy a 00/14 to.
Yes, I will update you on the testing on the 00/03.
I will start with a "simple" DPL first, and then put more devices in the list.

**Comment by karloygard** [comment]
Any further progress to report with the 00/03?  Should work just fine, but will be missing some newer functionality like e.g. extended status messages.  Not sure how well it will work with new devices.

**Comment by terosm** [comment]
Have tested both old and new Switching Actuator, Dimming Actuator. 
They works fine.
Today I am trying to get control over a Room Controller Touch (CRCA-00/08) and a CHAU-01/01-16E. Have some of these.
Have got a new CI 00/14 now , so I think the old one will be used on my other location where there are only switching- and dimming actuators so far.
I am impressed about your work on this addons solution. Have done some reverse engineering / decoding on xcomfort earlier, but nothing like this. 
I will continue to work with both the 00/03 and the new 00/14 i HA and combine xcomfort, with  hue, wifi, zigbee and so on.

**Comment by terosm** [comment]
Moving my xcomfort devices from Sensio to HA.

**Comment by karloygard** [comment]
> Today I am trying to get control over a Room Controller Touch (CRCA-00/08) and a CHAU-01/01-16E. Have some of these.

CHAU-01/01 support is pending the fix for https://github.com/karloygard/xcomfortd-go/issues/25.

**Comment by terosm** [comment]
Addon 0.38, MRF 2.73, CI 00/03
CHAU-01/01-16E , can control the switch, reading the "effekt" value, reading energi  value ( 1,185.535 kWh ??  ).
The connections between CI 00/03, CRCA-00/08 and a CHAU-01/01-16E regarding temperature and/or switching can be setup in different ways.
Trying different alternativs now.

**Comment by karloygard** [comment]
Send me a log with the unexpected value?

**Comment by terosm** [comment]
Sorry, for the delay and I have a type.
It is not a CHAU-01/01-16E this test was done  to, but a CHAP-01/F5-12E sw. 2.21 , Switching Plug 12A. Not PWM. 

Here is the energy message. from HA log
2021/08/22 16:54:41 RX: [c1146211000012178a31100a]
2021/08/22 16:54:41 Device 7306512 (channel 2-'Panelovn Kjellerstue (Energi)') sent message (battery mains-powered, signal good, cyclic false) event 'value' with value 1185.674
In the log from MRF it show the same. I think it is 1185,674 Wh.

- I can do switching from HA but not read temp or the set temp from RCT CRCA-00/08.  Only read "Fuktighet" ch1.
  ch0 shows : Payload: 1185.507 all the time ( not sure if the number is the same for every startup).
  But the CRCA-00/08 can't control the switch in CHAP-01/F5-12E.

- If I do a different configuration i MRF,  the RCT can control the switching plug, but HA not.
Still not able to see/read temp from the RCT.

**Comment by terosm** [comment]
Devidces and Part of the datapoint file and startuplog HA.
MRF 2.73
Sensor : CRCA-00/08 sw.2.05L /3.00L
Actuator : CHAP-01/F5-12E sw. 2.21  Switching Plug 12A
Datapoint:
15	Sensor Kjellerstue   (Temperatur)	7418264	78	0	0	1	#001#000#000#000#0#000#000#002#005#000#	
16	Sensor Kjellerstue   (Fuktighet)	7418264	78	1	1	1	#001#000#000#000#0#000#000#002#005#000#	
17	Sensor Kjellerstue   (Touch-sensor A)	7418264	78	4	0	1	#001#000#000#000#0#000#000#002#005#000#	
18	Sensor Kjellerstue   (Touch-sensor B)	7418264	78	5	0	1	#001#000#000#000#0#000#000#002#005#000#	
19	Panelovn Kjellerstue  (Aktuator)	7306512	74	0	0	0	#000#000#000#000#0#000#000#002#021#014#	
20	Panelovn Kjellerstue  (Energi)	7306512	74	2	0	1	#000#000#000#000#0#000#000#002#021#014#	
23	Panelovn Kjellerstue  (Effekt)	7306512	74	3	0	1	#000#000#000#000#0#000#000#002#021#014#	


2021/08/22 16:29:31 Starting xcomfortd, version 0.38
..
2021/08/22 16:29:31 Datapoint 19: device Switching Actuator New Generation (CSAU-01/01-1xxx), serial 7306512, channel 0, 'Panelovn Kjellerstue (Aktuator)'
2021/08/22 16:29:31 Datapoint 15: device Room Controller Touch (CRCA-00/xx), serial 7418264, channel 0, 'Sensor Kjellerstue (Temperatur)'
2021/08/22 16:29:31 Datapoint 16: device Room Controller Touch (CRCA-00/xx), serial 7418264, channel 1, 'Sensor Kjellerstue (Fuktighet)'
2021/08/22 16:29:31 Datapoint 17: device Room Controller Touch (CRCA-00/xx), serial 7418264, channel 4, 'Sensor Kjellerstue (Touch-sensor A)'
2021/08/22 16:29:31 Datapoint 18: device Room Controller Touch (CRCA-00/xx), serial 7418264, channel 5, 'Sensor Kjellerstue (Touch-sensor B)'
2021/08/22 16:29:31 Datapoint 20: device Switching Actuator New Generation (CSAU-01/01-1xxx), serial 7306512, channel 2, 'Panelovn Kjellerstue (Energi)'
2021/08/22 16:29:31 Datapoint 23: device Switching Actuator New Generation (CSAU-01/01-1xxx), serial 7306512, channel 3, 'Panelovn Kjellerstue (Effekt)'
2021/08/22 16:29:31 Connecting to MQTT broker 'tcp://core-mosquitto:1883' with id 'xcomfort'
2021/08/22 16:29:31 CONFIG: [b21b10]
[WARN]  [store]    memorystore wiped
2021/08/22 16:29:31 Connected to broker
2021/08/22 16:29:31 STATUS: [c31b10035c02b7]
2021/08/22 16:29:31 CI HW/RF/FW revision: 3, 9.2, 695
2021/08/22 16:29:31 CONFIG: [b21b00]
2021/08/22 16:29:31 STATUS: [c31b000902023c]
2021/08/22 16:29:31 CI RF/Firmware release: 9.02, 2.60
2021/08/22 16:29:31 CONFIG: [b20e00]
2021/08/22 16:29:31 STATUS: [c30e0000401ff7]
2021/08/22 16:29:31 CI serial number: 4202487
2021/08/22 16:29:31 CONFIG: [b20401]
2021/08/22 16:29:31 STATUS: [c31c0500000000]
2021/08/22 16:29:31 CONFIG: [b21e01]
2021/08/22 16:29:31 STATUS: [c31c0500000000]
2021/08/22 16:29:31 Datapoint 15 using partially supported mode; ignoring switching commands
2021/08/22 16:29:31 Sent MQTT autodiscover add for 19 devices and 24 datapoints

**Comment by karloygard** [comment]
Energy should already work. I've actually never tested it myself, will do so and report back.

None of the new heating actuators are properly supported yet. Another user has kindly agreed to lend me one for testing, so support may show up soon.

**Comment by karloygard** [comment]
I tested the energy measurement yesterday and it seems to work just fine. Energy shows up as a related entity on the actuator. The measurement is in kWh and looks like the accumulated energy that has been switched by the actuator, i.e. in your case 1185,674 kWh has been used by the oven. I couldn't find a way of resetting that value.

**Comment by terosm** [comment]
I also done a test on this today with an oven, you are rigth, it is kWh. 
I do not think  resetting is an option. Energy should be accumulated I think.

**Comment by terosm** [comment]
I still use the CKOZ-00/03 connected to the HA, but will change to CKHOZ-00/14 here at home.
The old CI I will use with a HA at another location where it is so far, only switches and dimmers.
 Which issue number do you want to continue the energy testing/discussion ? A new ?
 I still want to look at the possibilities with RCT and energy actuators.

**Comment by karloygard** [comment]
There is already an issue for this: https://github.com/karloygard/xcomfortd-go/issues/25, just tag along with that.
