### ISSUE TITLE
Issue when reading eprom

### ISSUE THREAD

**Issue by geeewizzz** [karloygard/hassio-addons#17]
After upgrading to Home Assistant Core to core-2021.8.5 (not sure if it is related), I experience that the add-on dies while reading the eprom, I've seen the issue consistently after retrying 6-7 times now. Sometimes it dies early in the initialization, sometimes late in the process, but i have yet to experience it completing.

When I switch to using hidapi it seems to be working fine.

I have turned on verbose and it doesn't give any info when it seemingly dies (13:15:47). It just stops reading and gives the occasional error when it's not able to interpret incoming messages to the usb-stick.

> 2021/08/10 13:15:46 EPROM: [d111a80a01800a00687962656c2073747565]
2021/08/10 13:15:46 EPROM: [d111b20a01800a002074616b20202844696d]
2021/08/10 13:15:46 EPROM: [d111bc0a01800a006d65616b747561746f72]
2021/08/10 13:15:47 EPROM: [d111c60a01800a0029000000000000000000]
2021/08/10 13:15:47 EPROM: [d111d00a01800a0000000000000000000000]
2021/08/10 13:15:47 EPROM: [d111da0a01800a0000000001040305200112]
2021/08/10 13:15:47 EPROM: [d111e40a01800a0040000000687962656c20]
2021/08/10 13:15:47 Datapoint 27: device Dimming Actuator New Generation (CDAx-01/xx), serial 6882335, channel 0, mode 0, 'hybel stue tak (Dimmeaktuator)'
2021/08/10 13:15:47 Level: 3.1.0, location [Leilighet, Stue/Kj�kken, ]
2021/08/10 13:15:47 EPROM: [d111e80a01800a00687962656c206b6af86b]
2021/08/10 13:15:47 EPROM: [d111f20a01800a006b656e2074616b202028]
2021/08/10 13:15:47 EPROM: [d111fc0a01800a0044696d6d65616b747561]
2021/08/10 13:16:41 RX: [c13e620300010200003a240a]
2021/08/10 13:16:41 Received message from unknown datapoint 62
2021/08/10 13:16:41 Message not handled [c13e620300010200003a240a]
2021/08/10 13:18:09 RX: [c13662170000e2010031240c]
2021/08/10 13:18:09 Received message from unknown datapoint 54
2021/08/10 13:18:09 Message not handled [c13662170000e2010031240c]
2021/08/10 13:19:21 RX: [c13b6204004246cccd392400]
2021/08/10 13:19:21 Received message from unknown datapoint 59
2021/08/10 13:19:21 Message not handled [c13b6204004246cccd392400]

**Comment by karloygard** [comment]
I pushed 0.38 with some extra logging just now. Please give it a shot and see what is logged.

**Comment by geeewizzz** [comment]
Bumped version, now i cant reproduce it, so it must have been an issue on my end or something.
