### ISSUE TITLE
CSAU-01/01-16IE supported?

### ISSUE THREAD

**Issue by dreeas** [karloygard/hassio-addons#20]
Hi,

I tried to add the CSAU-01/01-16IE (switch with energy measurement) to my setup and confirmed it working in MRF but all the entities show as disabled in the MQTT integration. Are these devices supported?

Log from the addon:
2021/09/10 09:29:17 RX: [c100733900520570004a072111000000491008]
2021/09/10 09:29:17 Device 7341394, type CSAU 01/01-16IE sent extended status message: status ON, temp 17C, power 0.0W (battery mains-powered, signal normal)
2021/09/10 09:29:52 RX: [c13b62210000000000491008]
2021/09/10 09:29:52 Device 7341394 (channel 3-'VVB (Effekt)') sent message (battery mains-powered, signal normal, cyclic false) event 'value' with value 0

**Comment by karloygard** [comment]
It's supported. When the devices show up as disabled, it's usually because HA was restarted, but not the add-on. HA is supposed to send an MQTT birth message, but for some reason this doesn't always work, causing the add-on not to restart MQTT discovery.

Restarting the add-on should resolve your issue.

**Comment by dreeas** [comment]
Thanks for a quick reply.

That was my first thoughts as well so I have restarted the addons several times, and also restarted HA itself several times but still it is showing as disabled.
It is being discovered Ok as shown in the logs:

2021/09/10 10:34:40 Datapoint 58: device Switching Actuator New Generation (CSAU-01/01-1xxx), serial 7341394, channel 2, mode 0, 'VVB (Energi)'
2021/09/10 10:34:40 EXTENDED: [d110a81b01800a00]
2021/09/10 10:34:40 EPROM: [d111a81b01800a0056564220202845666665]
2021/09/10 10:34:40 EXTENDED: [d110b21b01800a00]
2021/09/10 10:34:40 EPROM: [d111b21b01800a006b742900000000000000]
2021/09/10 10:34:40 EXTENDED: [d110bc1b01800a00]
2021/09/10 10:34:40 EPROM: [d111bc1b01800a0000000000000000000000]
2021/09/10 10:34:40 EXTENDED: [d110c61b01800a00]
2021/09/10 10:34:40 EPROM: [d111c61b01800a0000000000000000000000]
2021/09/10 10:34:40 EXTENDED: [d110d01b01800a00]
2021/09/10 10:34:41 EPROM: [d111d01b01800a0000000000000000000000]
2021/09/10 10:34:41 EXTENDED: [d110da1b01800a00]
2021/09/10 10:34:41 EPROM: [d111da1b01800a00000000010a0000000000]
2021/09/10 10:34:41 EXTENDED: [d110e41b01800a00]
2021/09/10 10:34:41 EPROM: [d111e41b01800a0000000000a900b1c95405]
2021/09/10 10:34:41 EXTENDED: [d110ee1b01800a00]
2021/09/10 10:34:41 EPROM: [d111ee1b01800a0027000020000000000000]
2021/09/10 10:34:41 Datapoint 59: device Switching Actuator New Generation (CSAU-01/01-1xxx), serial 7341394, channel 3, mode 0, 'VVB (Effekt)'

**Comment by karloygard** [comment]
Looks kosher. Can you delete the devices in HA and restart the add-on? This should repopulate the device list.

**Comment by dreeas** [comment]
That did the trick, thanks. Strange thing.
