### ISSUE TITLE
Addon failing with s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by dreeas** [karloygard/hassio-addons#23]
Was assisting a friend with troubleshooting his addon, he gets the fault log message: 
s6-overlay-suexec: fatal: can only run as pid 1
He had updated his HA to newest version.

Googling the fault and I found this: 
https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/?fbclid=IwAR2tDHcd5FaDULTmjzJ9gK2i4OS6_768rDwLvDxroFMbFX47irfSyGJAx8o

It was tested by adding init: false to the configuration and restarting HA, but it did not help. 

Any suggestions?

**Comment by karloygard** [comment]
Noted, something needs to be updated.

**Comment by dreeas** [comment]
Good to know, appriciate the quick feedback.

**Comment by karloygard** [comment]
Give it a shot now, 0.54.2 has hopefully fixed the issue.
