### ISSUE TITLE
Xcomfort switch to dim Hue lightbulb

### ISSUE THREAD

**Issue by geeewizzz** [karloygard/hassio-addons#8]
I have added an xcomfort light switch to be controlled by HA, i want it to control a Hue light bulb. I can easily get it to turn on and off, but do you have an example config of an automation where it is also dimming? I see the events for long press etc, so I assume it is possible. If you have it figured out already please send me the code so i can steal it, would save me some time :)

**Comment by karloygard** [comment]
Sorry, I haven't attempted this yet, I currently only have xComfort dimmers. If you figure it out, please post how you sorted it out!
