### ISSUE TITLE
hidapi: unknown failure

### ISSUE THREAD

**Issue by geeewizzz** [karloygard/hassio-addons#9]
> 2020/09/08 06:25:35 hidapi: unknown failure
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

My adddon shut down this morning, got the above error msg.

**Comment by karloygard** [comment]
That error comes from https://github.com/karalabe/hid/blob/master/hid_enabled.go somewhere. How long had the service been running? I assume no one touched the USB stick?

**Comment by karloygard** [comment]
I've pushed a new build that logs errors better, but this looks like an external issue to the daemon itself. The stick may have disconnected or some service was restarted? A workaround could be that the daemon just restarts, but it would be nice to understand what caused this.

Can you see anything else in HA logs from around that time?

**Comment by geeewizzz** [comment]
I updated HA to a new version later that evening. The xcomfort addon and HA had been running for about 12-16hrs before it crashed, the pi and the stick is in a cabinet and was not touched in the timeframe, no.

I have updated to the newest version of the xcomfort addon now, will keep an eye on it and report back with more logs if it happens again.

**Comment by karloygard** [comment]
hidapi appears to have stability issues and is only provided for testing purposes. By default, libusb is used and is stable.
